WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

file = _{ SOI ~ (import)* ~ (definitions)+ ~ EOI }

import = { "import" ~ filename  }
filename = @{ ( ASCII_ALPHANUMERIC | "_" | "/" | "." )+ }

definitions = _{ (agg | ent)+ }

agg = { "def agg " ~ name ~ label ~ "{" ~ "}" } 
ent = { "def ent " ~ name ~ label ~ parent ~ "{" ~ "}" } 

name = @{ (ASCII_ALPHA_LOWER | "_" )+ }
agg_name = { name }

label = @{ "\"" ~ (LETTER | SPACING_MARK)+ ~ "\"" }

parent = { "for "  ~ name }